/**
 * Expo config plugin: give MainActivity an `onNewIntent` override that calls
 * `setIntent(intent)`.
 *
 * MainActivity is `singleTask`, so tapping Answer / the full-screen intent on an
 * incoming-call notification RESUMES the existing activity — the call extras
 * arrive in onNewIntent, not onCreate. React Native's ReactActivity forwards that
 * intent to the React/Expo listeners but never calls `setIntent()`, so
 * `getIntent()` keeps returning the ORIGINAL launch intent for the life of the
 * activity.
 *
 * ExpoCallUiModule reads the CURRENT activity's intent in `getInitialCallAction()`
 * (and the cold-start cover's peek). Without setIntent() those read a stale intent:
 * they can replay a long-consumed call action — answering a call that is already
 * over — while the call actually being answered is missed.
 *
 * This must be a config plugin, not a hand-edit: `android/` is regenerated by
 * `expo prebuild --clean` / EAS, which overwrites MainActivity.kt from the Expo
 * template and would silently drop the override.
 *
 * Idempotent: re-running prebuild (or this plugin) will not double-insert.
 */
const { withMainActivity } = require('@expo/config-plugins');

const INTENT_IMPORT = 'import android.content.Intent';

const ON_NEW_INTENT = `
  /**
   * MainActivity is singleTask: an Answer / full-screen tap on an incoming-call
   * notification resumes THIS instance, so the call extras land here. ReactActivity
   * never calls setIntent(), which would leave getIntent() pinned to the original
   * launch intent — and the call module reads the current activity's intent to learn
   * which call to answer. Store the fresh intent first, then hand it on so the
   * module's OnNewIntent listener still fires.
   */
  override fun onNewIntent(intent: Intent) {
    setIntent(intent)
    super.onNewIntent(intent)
  }
`;

const withCallOnNewIntent = (config) =>
  withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        '[withCallOnNewIntent] expected a Kotlin MainActivity; got ' +
          cfg.modResults.language,
      );
    }

    let contents = cfg.modResults.contents;

    // Already applied (e.g. prebuild re-run without --clean) → leave it alone.
    if (contents.includes('override fun onNewIntent')) {
      return cfg;
    }

    // 1) Make sure android.content.Intent is imported.
    if (!contents.includes(INTENT_IMPORT)) {
      // Anchor on an import the Expo template always emits.
      const anchor = 'import android.os.Bundle';
      if (!contents.includes(anchor)) {
        throw new Error('[withCallOnNewIntent] could not find an import anchor in MainActivity');
      }
      contents = contents.replace(anchor, `${INTENT_IMPORT}\n${anchor}`);
    }

    // 2) Insert the override just before getMainComponentName, which the template
    //    always declares.
    const methodAnchor = '  override fun getMainComponentName()';
    if (!contents.includes(methodAnchor)) {
      throw new Error('[withCallOnNewIntent] could not find getMainComponentName in MainActivity');
    }
    contents = contents.replace(methodAnchor, `${ON_NEW_INTENT}\n${methodAnchor}`);

    cfg.modResults.contents = contents;
    return cfg;
  });

module.exports = withCallOnNewIntent;
