/**
 * Expo config plugin: add an iOS Notification Service Extension (NSE) so killed/
 * backgrounded message pushes render as WhatsApp-style COMMUNICATION notifications
 * (sender avatar + name, per-chat threading) instead of a plain single-line alert.
 *
 * Why an NSE is required: when the app is killed, no JS runs on iOS — the OS draws
 * the APNs alert itself. The ONLY way to upgrade that notification (download the
 * avatar, build an INSendMessageIntent communication notification, set the thread)
 * before it is shown is a Notification Service Extension, which the OS launches for
 * any push carrying `mutable-content: 1` (the backend sets that in Step 5).
 *
 * `ios/` is git-ignored (Continuous Native Generation), so the whole NSE target —
 * its Swift source, Info.plist, entitlements, Xcode target wiring, and the App
 * Group / communication entitlements on the main app — must be (re)generated by
 * this plugin on every `expo prebuild` / EAS build.
 *
 * After adding this to app.json, run:  expo prebuild --clean -p ios  then build.
 *
 * NOTE: pbxproj target wiring cannot be compiled on a non-macOS host, so verify
 * the first iOS build in Xcode (target "NotificationServiceExtension" should embed
 * in the app under "Embed App Extensions").
 */
const {
  withInfoPlist,
  withEntitlementsPlist,
  withXcodeProject,
  withDangerousMod,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const NSE_TARGET_NAME = 'NotificationServiceExtension';
const NSE_SOURCE_NAME = 'NotificationService.swift';
const DEPLOYMENT_TARGET = '15.0';

// App Group that both the main app and the NSE share (cross-process dedupe store).
const appGroupFor = (bundleId) => `group.${bundleId}.notifications`;

// ─── NSE Swift source ───
const nseSwiftSource = (appGroup) => `import UserNotifications
import Intents
import UIKit

// Notification Service Extension — upgrades incoming message pushes into
// WhatsApp-style communication notifications. Generated by
// plugins/withNotificationServiceExtension.js — edit there, not here.
//
// DELIVERY IS THE CONTRACT; everything else here is decoration. The extension
// runs BEFORE iOS shows the notification, so every millisecond it spends is a
// millisecond the user does not see the message — and if it never calls the
// content handler (a hung download, or a jetsam kill against the extension's
// small memory budget) the notification can be dropped ENTIRELY. Hence:
//
//   1. ONE-SHOT DELIVERY — \`deliver()\` fires once, from whichever happens first:
//      the avatar fetch, our own deadline, or the OS's
//      serviceExtensionTimeWillExpire. Calling the handler twice is undefined
//      behaviour; never calling it loses the notification.
//   2. A HARD DEADLINE — the avatar fetch gets \`avatarTimeout\` and the whole
//      decoration gets \`deliveryDeadline\`, both far inside the OS's ~30 s. A
//      slow or unreachable avatar URL therefore costs the user an AVATAR, never
//      a late or missing notification. (Previously an unbounded
//      URLSession.shared request could hold the notification back ~30 s, and two
//      pushes arriving back-to-back shared one extension process — so a hang on
//      the first could cost both.)
class NotificationService: UNNotificationServiceExtension {
  static let appGroup = "${appGroup}"

  /// Whole-extension budget: past this we show what we already have.
  private static let deliveryDeadline: TimeInterval = 5
  /// Per-request budget for the avatar fetch.
  private static let avatarTimeout: TimeInterval = 4
  /// Bigger avatars are ignored — decoding one can overrun the extension's
  /// memory budget, and that takes the notification down with it.
  private static let maxAvatarBytes = 512 * 1024

  private var contentHandler: ((UNNotificationContent) -> Void)?
  private var bestAttempt: UNMutableNotificationContent?
  private var deadlineWork: DispatchWorkItem?
  private var avatarSession: URLSession?
  private let lock = NSLock()

  override func didReceive(_ request: UNNotificationRequest,
                           withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
    self.contentHandler = contentHandler

    guard let mutable = request.content.mutableCopy() as? UNMutableNotificationContent else {
      deliver(request.content)
      return
    }
    self.bestAttempt = mutable

    let data = request.content.userInfo
    let senderName = (data["senderName"] as? String) ?? mutable.title
    let chatId = (data["chatId"] as? String) ?? ""
    let senderId = (data["senderId"] as? String) ?? senderName
    let isGroup = (data["chatType"] as? String) == "group"
    let groupName = (data["groupName"] as? String) ?? ""
    let avatarURLString = (data["profileImage"] as? String) ?? ""

    // Per-chat threading so the tray groups a conversation's notifications.
    if !chatId.isEmpty { mutable.threadIdentifier = chatId }

    recordShown(messageId: data["messageId"] as? String)

    // Armed BEFORE any async work, so nothing can outlive it.
    armDeadline()

    guard #available(iOS 15.0, *) else { deliver(mutable); return }

    decorate(content: mutable, senderName: senderName, senderId: senderId,
             chatId: chatId, isGroup: isGroup, groupName: groupName,
             avatarURL: avatarURLString)
  }

  override func serviceExtensionTimeWillExpire() {
    // The OS is out of patience — deliver whatever we have.
    deliver(nil)
  }

  // ─── One-shot delivery ───
  // Thread-safe and idempotent: the first caller wins and every later one is a
  // no-op, so the download completing just after the deadline fired can never
  // call the handler a second time. \`nil\` means "use the best attempt".
  private func deliver(_ content: UNNotificationContent?) {
    lock.lock()
    guard let handler = contentHandler else { lock.unlock(); return }
    contentHandler = nil
    let work = deadlineWork
    let session = avatarSession
    let fallback = bestAttempt
    deadlineWork = nil
    avatarSession = nil
    lock.unlock()

    work?.cancel()
    session?.invalidateAndCancel()
    handler(content ?? fallback ?? UNMutableNotificationContent())
  }

  private func armDeadline() {
    let work = DispatchWorkItem { [weak self] in self?.deliver(nil) }
    lock.lock()
    deadlineWork = work
    lock.unlock()
    DispatchQueue.global(qos: .userInitiated).asyncAfter(
      deadline: .now() + NotificationService.deliveryDeadline, execute: work)
  }

  // Record the messageId in the shared App Group so the JS layer can see what
  // the OS already showed (cross-process dedupe signal).
  private func recordShown(messageId: String?) {
    guard let messageId = messageId, !messageId.isEmpty,
          let defaults = UserDefaults(suiteName: NotificationService.appGroup) else { return }
    var seen = defaults.array(forKey: "shownMessageIds") as? [String] ?? []
    if seen.contains(messageId) { return }
    seen.append(messageId)
    if seen.count > 200 { seen = Array(seen.suffix(200)) }
    defaults.set(seen, forKey: "shownMessageIds")
  }

  @available(iOS 15.0, *)
  private func decorate(content: UNMutableNotificationContent, senderName: String, senderId: String,
                        chatId: String, isGroup: Bool, groupName: String, avatarURL: String) {
    let finish: (INImage?) -> Void = { [weak self] image in
      guard let self = self else { return }
      self.deliver(self.communicationContent(
        content: content, senderName: senderName, senderId: senderId,
        chatId: chatId, isGroup: isGroup, groupName: groupName, image: image))
    }

    // Only a real network URL is worth a round-trip. Anything else (empty,
    // relative, file:, data:) goes straight to delivery with no avatar.
    guard let url = URL(string: avatarURL),
          let scheme = url.scheme?.lowercased(),
          scheme == "https" || scheme == "http",
          url.host != nil else {
      finish(nil)
      return
    }

    let config = URLSessionConfiguration.ephemeral
    config.timeoutIntervalForRequest = NotificationService.avatarTimeout
    config.timeoutIntervalForResource = NotificationService.avatarTimeout
    config.waitsForConnectivity = false
    let session = URLSession(configuration: config)
    lock.lock()
    avatarSession = session
    lock.unlock()

    let task = session.dataTask(with: url) { data, response, _ in
      session.finishTasksAndInvalidate()
      finish(NotificationService.avatarImage(from: data, response: response))
    }
    task.resume()
  }

  // Turn the downloaded bytes into something INImage renders reliably, or
  // nothing at all. Re-encoding through UIImage means a format INImage decodes
  // inconsistently (the avatar pipeline stores .webp) still reaches the
  // notification, and a non-image body (an HTML error page) is rejected instead
  // of drawn as a blank square.
  private static func avatarImage(from data: Data?, response: URLResponse?) -> INImage? {
    guard let data = data, !data.isEmpty, data.count <= maxAvatarBytes else { return nil }
    if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) { return nil }
    guard let decoded = UIImage(data: data) else { return nil }
    if let jpeg = decoded.jpegData(compressionQuality: 0.8) { return INImage(imageData: jpeg) }
    return INImage(imageData: data)
  }

  @available(iOS 15.0, *)
  private func communicationContent(content: UNMutableNotificationContent, senderName: String,
                                    senderId: String, chatId: String, isGroup: Bool,
                                    groupName: String, image: INImage?) -> UNNotificationContent {
    let handle = INPersonHandle(value: senderId, type: .unknown)
    let sender = INPerson(
      personHandle: handle, nameComponents: nil, displayName: senderName,
      image: image, contactIdentifier: nil, customIdentifier: senderId,
      isMe: false, suggestionType: .none
    )
    let intent = INSendMessageIntent(
      recipients: nil,
      outgoingMessageType: .outgoingMessageText,
      content: content.body,
      speakableGroupName: isGroup ? INSpeakableString(spokenPhrase: groupName) : nil,
      conversationIdentifier: chatId.isEmpty ? nil : chatId,
      serviceName: nil,
      sender: sender,
      attachments: nil
    )
    if let image = image { intent.setImage(image, forParameterNamed: \\.sender) }

    let interaction = INInteraction(intent: intent, response: nil)
    interaction.direction = .incoming
    interaction.donate(completion: nil)

    do {
      return try content.updating(from: intent)
    } catch {
      return content
    }
  }
}`;

// The App Store rejects/warns when an extension's version does not match the
// containing app (ITMS-90473), so mirror the app's version + build number here.
const nseInfoPlist = (version, buildNumber) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDisplayName</key>
  <string>NotificationServiceExtension</string>
  <!-- REQUIRED: names the extension's binary. Without it the built .appex has no
       CFBundleExecutable and iOS refuses to install the host app ("has missing or
       invalid CFBundleExecutable"). Xcode does NOT auto-inject it for a manual
       INFOPLIST_FILE, so declare it explicitly. $(EXECUTABLE_NAME) → the product. -->
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key>
  <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key>
  <string>${version}</string>
  <key>CFBundleVersion</key>
  <string>${buildNumber}</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.usernotifications.service</string>
    <key>NSExtensionPrincipalClass</key>
    <string>$(PRODUCT_MODULE_NAME).NotificationService</string>
  </dict>
</dict>
</plist>
`;

const nseEntitlements = (appGroup) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${appGroup}</string>
  </array>
</dict>
</plist>
`;

// ─── 1) Main-app entitlements: App Group + communication notifications ───
const withMainAppEntitlements = (config, appGroup) =>
  withEntitlementsPlist(config, (cfg) => {
    const groups = cfg.modResults['com.apple.security.application-groups'] || [];
    if (!groups.includes(appGroup)) groups.push(appGroup);
    cfg.modResults['com.apple.security.application-groups'] = groups;
    // Required for INSendMessageIntent-based communication notifications (iOS 15+).
    cfg.modResults['com.apple.developer.usernotifications.communication'] = true;
    return cfg;
  });

// ─── 2) Write NSE source files into ios/<NSE_TARGET_NAME>/ ───
const withNSEFiles = (config, appGroup) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot;
      const nseDir = path.join(iosRoot, NSE_TARGET_NAME);
      fs.mkdirSync(nseDir, { recursive: true });
      fs.writeFileSync(path.join(nseDir, NSE_SOURCE_NAME), nseSwiftSource(appGroup));
      fs.writeFileSync(
        path.join(nseDir, 'Info.plist'),
        nseInfoPlist(cfg.version || '1.0', cfg.ios?.buildNumber || '1'),
      );
      fs.writeFileSync(
        path.join(nseDir, `${NSE_TARGET_NAME}.entitlements`),
        nseEntitlements(appGroup),
      );
      return cfg;
    },
  ]);

// ─── 3) Wire the NSE target into the Xcode project ───
const withNSETarget = (config, appGroup) =>
  withXcodeProject(config, (cfg) => {
    const proj = cfg.modResults;
    const bundleId = cfg.ios.bundleIdentifier;
    const nseBundleId = `${bundleId}.${NSE_TARGET_NAME}`;

    // Idempotent: skip if the target already exists (re-running prebuild).
    if (proj.pbxTargetByName(NSE_TARGET_NAME)) return cfg;

    // Group holding the NSE files in the project navigator.
    const groupKey = proj.pbxCreateGroup(NSE_TARGET_NAME, NSE_TARGET_NAME);

    // Create the app-extension target.
    const target = proj.addTarget(NSE_TARGET_NAME, 'app_extension', NSE_TARGET_NAME, nseBundleId);

    // Build phases the target needs.
    proj.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    proj.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);
    proj.addBuildPhase(
      ['UserNotifications.framework', 'Intents.framework'],
      'PBXFrameworksBuildPhase',
      'Frameworks',
      target.uuid,
    );

    // Add the Swift source to the group + the target's Sources phase.
    proj.addSourceFile(
      `${NSE_TARGET_NAME}/${NSE_SOURCE_NAME}`,
      { target: target.uuid },
      groupKey,
    );

    // Per-target build settings (deployment target, bundle id, plist, entitlements).
    const configurations = proj.pbxXCBuildConfigurationSection();
    for (const key in configurations) {
      const bs = configurations[key].buildSettings;
      if (!bs || bs.PRODUCT_NAME !== `"${NSE_TARGET_NAME}"`) continue;
      bs.PRODUCT_BUNDLE_IDENTIFIER = `"${nseBundleId}"`;
      bs.INFOPLIST_FILE = `"${NSE_TARGET_NAME}/Info.plist"`;
      bs.CODE_SIGN_ENTITLEMENTS = `"${NSE_TARGET_NAME}/${NSE_TARGET_NAME}.entitlements"`;
      bs.IPHONEOS_DEPLOYMENT_TARGET = DEPLOYMENT_TARGET;
      bs.TARGETED_DEVICE_FAMILY = '"1,2"';
      bs.SWIFT_VERSION = '5.0';
      bs.CODE_SIGN_STYLE = 'Automatic';
      bs.CLANG_ENABLE_MODULES = 'YES';
      bs.MARKETING_VERSION = cfg.version || '1.0';
      bs.CURRENT_PROJECT_VERSION = cfg.ios?.buildNumber || '1';
    }

    // Make the app DEPEND on the extension. We deliberately do NOT add an explicit
    // "Embed App Extensions" copy phase: node-xcode's addTarget() ALREADY creates a
    // "Copy Files" phase (PlugIns / dstSubfolderSpec 13) in the app target and
    // embeds the .appex into it for an 'app_extension' target (see
    // xcode/lib/pbxProject.js addTarget, targetType === 'app_extension'). Adding a
    // second embed phase made Xcode schedule TWO identical copy +
    // ValidateEmbeddedBinary tasks for the same appex → "Unexpected duplicate
    // tasks" (xcodebuild error 65). One embed (from addTarget) is all that's needed.
    const appTarget = proj.getFirstTarget().uuid;
    proj.addTargetDependency(appTarget, [target.uuid]);

    // Break the Xcode 15/16 "Cycle inside <app>; building could produce unreliable
    // results" error. node-xcode's addTarget() appends the app-extension embed
    // phase ("Copy Files" → PlugIns) as the LAST build phase — AFTER the
    // "[CP-User] [RNFB] Core Configuration" script phase, which declares the app
    // Info.plist as an input and rewrites it (PlistBuddy). Xcode then sees a cycle:
    // embed appex → (runs after) RNFB script → Info.plist → ExtractAppIntentsMetadata
    // → (depends on) embed appex. The .appex is produced by the NSE target
    // dependency added just above, so the embed can run at ANY position and code
    // signing still happens last — moving the embed phase to the FRONT removes the
    // embed→RNFB edge and breaks the cycle. Guarded so a node-xcode internal-shape
    // change can never fail prebuild (the checked-in project keeps the same order).
    try {
      const appObj = proj.pbxNativeTargetSection()[appTarget];
      const phases = (appObj && appObj.buildPhases) || [];
      const copySection = proj.hash.project.objects.PBXCopyFilesBuildPhase || {};
      const embedIdx = phases.findIndex((ph) => {
        const obj = copySection[ph.value];
        return obj && obj.isa === 'PBXCopyFilesBuildPhase'
          && String(obj.dstSubfolderSpec) === '13'
          && (obj.files || []).some((f) => String(f.comment || '').includes(`${NSE_TARGET_NAME}.appex`));
      });
      if (embedIdx > 1) {
        const [embed] = phases.splice(embedIdx, 1);
        phases.splice(1, 0, embed); // before Sources / RNFB script
      }
    } catch (e) {
      // Non-fatal: leave phase order as-is; the committed project already has it.
    }

    return cfg;
  });

// ─── Compose ───
const withNotificationServiceExtension = (config) => {
  const bundleId = (config.ios && config.ios.bundleIdentifier) || 'com.chat.baatCheet';
  const appGroup = appGroupFor(bundleId);

  // Keep the app's NSExtension/Background entitlement intact; we only ADD.
  config = withMainAppEntitlements(config, appGroup);
  config = withNSEFiles(config, appGroup);
  config = withNSETarget(config, appGroup);
  // Ensure remote-notification background mode is present (already in app.json,
  // but assert it so the NSE wake path can never silently break).
  config = withInfoPlist(config, (cfg) => {
    const modes = cfg.modResults.UIBackgroundModes || [];
    if (!modes.includes('remote-notification')) modes.push('remote-notification');
    cfg.modResults.UIBackgroundModes = modes;
    return cfg;
  });
  return config;
};

module.exports = withNotificationServiceExtension;
