/**
 * Expo config plugin: add an iOS Notification Service Extension (NSE) so killed/
 * backgrounded message pushes render as WhatsApp-style COMMUNICATION notifications
 * (sender avatar + name, per-chat threading) instead of a plain single-line alert.
 *
 * Why an NSE is required: when the app is killed, no JS runs on iOS — the OS draws
 * the APNs alert itself. The ONLY way to upgrade that notification (download the
 * avatar, build an INSendMessageIntent communication notification, set the thread)
 * before it is shown is a Notification Service Extension, which the OS launches for
 * any push carrying `mutable-content: 1` (the backend sets that in Step 5).
 *
 * `ios/` is git-ignored (Continuous Native Generation), so the whole NSE target —
 * its Swift source, Info.plist, entitlements, Xcode target wiring, and the App
 * Group / communication entitlements on the main app — must be (re)generated by
 * this plugin on every `expo prebuild` / EAS build.
 *
 * After adding this to app.json, run:  expo prebuild --clean -p ios  then build.
 *
 * NOTE: pbxproj target wiring cannot be compiled on a non-macOS host, so verify
 * the first iOS build in Xcode (target "NotificationServiceExtension" should embed
 * in the app under "Embed App Extensions").
 */
const {
  withInfoPlist,
  withEntitlementsPlist,
  withXcodeProject,
  withDangerousMod,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const NSE_TARGET_NAME = 'NotificationServiceExtension';
const NSE_SOURCE_NAME = 'NotificationService.swift';
const DEPLOYMENT_TARGET = '15.0';

// App Group that both the main app and the NSE share (cross-process dedupe store).
const appGroupFor = (bundleId) => `group.${bundleId}.notifications`;

// ─── NSE Swift source ───
const nseSwiftSource = (appGroup) => `import UserNotifications
import Intents

// Notification Service Extension — upgrades incoming message pushes into
// WhatsApp-style communication notifications. Generated by
// plugins/withNotificationServiceExtension.js — edit there, not here.
class NotificationService: UNNotificationServiceExtension {
  static let appGroup = "${appGroup}"
  var contentHandler: ((UNNotificationContent) -> Void)?
  var bestAttempt: UNMutableNotificationContent?

  override func didReceive(_ request: UNNotificationRequest,
                           withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
    self.contentHandler = contentHandler
    guard let mutable = request.content.mutableCopy() as? UNMutableNotificationContent else {
      contentHandler(request.content); return
    }
    self.bestAttempt = mutable

    let data = request.content.userInfo
    let senderName = (data["senderName"] as? String) ?? mutable.title
    let chatId = (data["chatId"] as? String) ?? ""
    let senderId = (data["senderId"] as? String) ?? senderName
    let isGroup = (data["chatType"] as? String) == "group"
    let groupName = (data["groupName"] as? String) ?? ""
    let avatarURLString = (data["profileImage"] as? String) ?? ""

    // Per-chat threading so the tray groups a conversation's notifications.
    if !chatId.isEmpty { mutable.threadIdentifier = chatId }

    // Record the messageId in the shared App Group so the JS layer is aware of
    // what the OS already showed (cross-process dedupe signal).
    if let messageId = data["messageId"] as? String,
       let defaults = UserDefaults(suiteName: NotificationService.appGroup) {
      var seen = defaults.array(forKey: "shownMessageIds") as? [String] ?? []
      if !seen.contains(messageId) {
        seen.append(messageId)
        if seen.count > 200 { seen = Array(seen.suffix(200)) }
        defaults.set(seen, forKey: "shownMessageIds")
      }
    }

    guard #available(iOS 15.0, *) else { contentHandler(mutable); return }

    buildCommunicationNotification(
      content: mutable, senderName: senderName, senderId: senderId,
      chatId: chatId, isGroup: isGroup, groupName: groupName, avatarURL: avatarURLString
    ) { updated in contentHandler(updated) }
  }

  override func serviceExtensionTimeWillExpire() {
    // The OS is out of patience — deliver whatever we have.
    if let handler = contentHandler, let best = bestAttempt { handler(best) }
  }

  @available(iOS 15.0, *)
  private func buildCommunicationNotification(
    content: UNMutableNotificationContent, senderName: String, senderId: String,
    chatId: String, isGroup: Bool, groupName: String, avatarURL: String,
    completion: @escaping (UNNotificationContent) -> Void
  ) {
    let finish: (INImage?) -> Void = { image in
      let handle = INPersonHandle(value: senderId, type: .unknown)
      let sender = INPerson(
        personHandle: handle, nameComponents: nil, displayName: senderName,
        image: image, contactIdentifier: nil, customIdentifier: senderId,
        isMe: false, suggestionType: .none
      )
      let intent = INSendMessageIntent(
        recipients: nil,
        outgoingMessageType: .outgoingMessageText,
        content: content.body,
        speakableGroupName: isGroup ? INSpeakableString(spokenPhrase: groupName) : nil,
        conversationIdentifier: chatId.isEmpty ? nil : chatId,
        serviceName: nil,
        sender: sender,
        attachments: nil
      )
      if let image = image { intent.setImage(image, forParameterNamed: \\.sender) }

      let interaction = INInteraction(intent: intent, response: nil)
      interaction.direction = .incoming
      interaction.donate(completion: nil)

      do {
        let updated = try content.updating(from: intent)
        completion(updated)
      } catch {
        completion(content)
      }
    }

    // Best-effort avatar download (bounded — the NSE has ~30s before expiry).
    guard let url = URL(string: avatarURL), !avatarURL.isEmpty else { finish(nil); return }
    let task = URLSession.shared.dataTask(with: url) { data, _, _ in
      if let data = data { finish(INImage(imageData: data)) } else { finish(nil) }
    }
    task.resume()
  }
}
`;

const nseInfoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDisplayName</key>
  <string>NotificationServiceExtension</string>
  <!-- REQUIRED: names the extension's binary. Without it the built .appex has no
       CFBundleExecutable and iOS refuses to install the host app ("has missing or
       invalid CFBundleExecutable"). Xcode does NOT auto-inject it for a manual
       INFOPLIST_FILE, so declare it explicitly. $(EXECUTABLE_NAME) → the product. -->
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key>
  <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.usernotifications.service</string>
    <key>NSExtensionPrincipalClass</key>
    <string>$(PRODUCT_MODULE_NAME).NotificationService</string>
  </dict>
</dict>
</plist>
`;

const nseEntitlements = (appGroup) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${appGroup}</string>
  </array>
</dict>
</plist>
`;

// ─── 1) Main-app entitlements: App Group + communication notifications ───
const withMainAppEntitlements = (config, appGroup) =>
  withEntitlementsPlist(config, (cfg) => {
    const groups = cfg.modResults['com.apple.security.application-groups'] || [];
    if (!groups.includes(appGroup)) groups.push(appGroup);
    cfg.modResults['com.apple.security.application-groups'] = groups;
    // Required for INSendMessageIntent-based communication notifications (iOS 15+).
    cfg.modResults['com.apple.developer.usernotifications.communication'] = true;
    return cfg;
  });

// ─── 2) Write NSE source files into ios/<NSE_TARGET_NAME>/ ───
const withNSEFiles = (config, appGroup) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot;
      const nseDir = path.join(iosRoot, NSE_TARGET_NAME);
      fs.mkdirSync(nseDir, { recursive: true });
      fs.writeFileSync(path.join(nseDir, NSE_SOURCE_NAME), nseSwiftSource(appGroup));
      fs.writeFileSync(path.join(nseDir, 'Info.plist'), nseInfoPlist);
      fs.writeFileSync(
        path.join(nseDir, `${NSE_TARGET_NAME}.entitlements`),
        nseEntitlements(appGroup),
      );
      return cfg;
    },
  ]);

// ─── 3) Wire the NSE target into the Xcode project ───
const withNSETarget = (config, appGroup) =>
  withXcodeProject(config, (cfg) => {
    const proj = cfg.modResults;
    const bundleId = cfg.ios.bundleIdentifier;
    const nseBundleId = `${bundleId}.${NSE_TARGET_NAME}`;

    // Idempotent: skip if the target already exists (re-running prebuild).
    if (proj.pbxTargetByName(NSE_TARGET_NAME)) return cfg;

    // Group holding the NSE files in the project navigator.
    const groupKey = proj.pbxCreateGroup(NSE_TARGET_NAME, NSE_TARGET_NAME);

    // Create the app-extension target.
    const target = proj.addTarget(NSE_TARGET_NAME, 'app_extension', NSE_TARGET_NAME, nseBundleId);

    // Build phases the target needs.
    proj.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    proj.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);
    proj.addBuildPhase(
      ['UserNotifications.framework', 'Intents.framework'],
      'PBXFrameworksBuildPhase',
      'Frameworks',
      target.uuid,
    );

    // Add the Swift source to the group + the target's Sources phase.
    proj.addSourceFile(
      `${NSE_TARGET_NAME}/${NSE_SOURCE_NAME}`,
      { target: target.uuid },
      groupKey,
    );

    // Per-target build settings (deployment target, bundle id, plist, entitlements).
    const configurations = proj.pbxXCBuildConfigurationSection();
    for (const key in configurations) {
      const bs = configurations[key].buildSettings;
      if (!bs || bs.PRODUCT_NAME !== `"${NSE_TARGET_NAME}"`) continue;
      bs.PRODUCT_BUNDLE_IDENTIFIER = `"${nseBundleId}"`;
      bs.INFOPLIST_FILE = `"${NSE_TARGET_NAME}/Info.plist"`;
      bs.CODE_SIGN_ENTITLEMENTS = `"${NSE_TARGET_NAME}/${NSE_TARGET_NAME}.entitlements"`;
      bs.IPHONEOS_DEPLOYMENT_TARGET = DEPLOYMENT_TARGET;
      bs.TARGETED_DEVICE_FAMILY = '"1,2"';
      bs.SWIFT_VERSION = '5.0';
      bs.CODE_SIGN_STYLE = 'Automatic';
      bs.CLANG_ENABLE_MODULES = 'YES';
      bs.MARKETING_VERSION = '1.0';
      bs.CURRENT_PROJECT_VERSION = '1';
    }

    // Make the app DEPEND on the extension. We deliberately do NOT add an explicit
    // "Embed App Extensions" copy phase: node-xcode's addTarget() ALREADY creates a
    // "Copy Files" phase (PlugIns / dstSubfolderSpec 13) in the app target and
    // embeds the .appex into it for an 'app_extension' target (see
    // xcode/lib/pbxProject.js addTarget, targetType === 'app_extension'). Adding a
    // second embed phase made Xcode schedule TWO identical copy +
    // ValidateEmbeddedBinary tasks for the same appex → "Unexpected duplicate
    // tasks" (xcodebuild error 65). One embed (from addTarget) is all that's needed.
    const appTarget = proj.getFirstTarget().uuid;
    proj.addTargetDependency(appTarget, [target.uuid]);

    // Break the Xcode 15/16 "Cycle inside <app>; building could produce unreliable
    // results" error. node-xcode's addTarget() appends the app-extension embed
    // phase ("Copy Files" → PlugIns) as the LAST build phase — AFTER the
    // "[CP-User] [RNFB] Core Configuration" script phase, which declares the app
    // Info.plist as an input and rewrites it (PlistBuddy). Xcode then sees a cycle:
    // embed appex → (runs after) RNFB script → Info.plist → ExtractAppIntentsMetadata
    // → (depends on) embed appex. The .appex is produced by the NSE target
    // dependency added just above, so the embed can run at ANY position and code
    // signing still happens last — moving the embed phase to the FRONT removes the
    // embed→RNFB edge and breaks the cycle. Guarded so a node-xcode internal-shape
    // change can never fail prebuild (the checked-in project keeps the same order).
    try {
      const appObj = proj.pbxNativeTargetSection()[appTarget];
      const phases = (appObj && appObj.buildPhases) || [];
      const copySection = proj.hash.project.objects.PBXCopyFilesBuildPhase || {};
      const embedIdx = phases.findIndex((ph) => {
        const obj = copySection[ph.value];
        return obj && obj.isa === 'PBXCopyFilesBuildPhase'
          && String(obj.dstSubfolderSpec) === '13'
          && (obj.files || []).some((f) => String(f.comment || '').includes(`${NSE_TARGET_NAME}.appex`));
      });
      if (embedIdx > 1) {
        const [embed] = phases.splice(embedIdx, 1);
        phases.splice(1, 0, embed); // before Sources / RNFB script
      }
    } catch (e) {
      // Non-fatal: leave phase order as-is; the committed project already has it.
    }

    return cfg;
  });

// ─── Compose ───
const withNotificationServiceExtension = (config) => {
  const bundleId = (config.ios && config.ios.bundleIdentifier) || 'com.chat.baatCheet';
  const appGroup = appGroupFor(bundleId);

  // Keep the app's NSExtension/Background entitlement intact; we only ADD.
  config = withMainAppEntitlements(config, appGroup);
  config = withNSEFiles(config, appGroup);
  config = withNSETarget(config, appGroup);
  // Ensure remote-notification background mode is present (already in app.json,
  // but assert it so the NSE wake path can never silently break).
  config = withInfoPlist(config, (cfg) => {
    const modes = cfg.modResults.UIBackgroundModes || [];
    if (!modes.includes('remote-notification')) modes.push('remote-notification');
    cfg.modResults.UIBackgroundModes = modes;
    return cfg;
  });
  return config;
};

module.exports = withNotificationServiceExtension;
