/**
 * Expo config plugin: render incoming-call notifications NATIVELY, instantly.
 *
 * Problem it fixes: the incoming-call CallStyle notification was built in JS
 * (firebase `setBackgroundMessageHandler` → ExpoCallUi). On a KILLED app under
 * Doze, the React Native JS runtime cold-start takes several seconds, so the
 * notification appeared late — the caller's ring timed out first ("3-4 baar call
 * karta hu kaat kaat kar tab aata hai") and a backlog flushed at once on reopen.
 *
 * Fix: a native `FirebaseMessagingService` (CallMessagingService) that SUBCLASSES
 * react-native-firebase's own messaging service — so token refresh + message
 * delivery are 100% preserved by inheritance — and adds ONE behaviour: when a
 * `type:"call"` data push arrives it posts the CallStyle full-screen notification
 * natively (ExpoCallUiModule.renderIncoming), ~100-200ms from FCM arrival, BEFORE
 * the JS bridge boots. Stale buffered pushes (data.ts older than the ring window)
 * are dropped so a flushed backlog can't ring many dead calls at once.
 *
 * `android/` is CNG (regenerated by prebuild), so this MUST be a config plugin:
 *   1. withDangerousMod — write CallMessagingService.kt into the app package.
 *   2. withAndroidManifest — register the <service> for com.google.firebase
 *      .MESSAGING_EVENT with a higher intent-filter priority than RNFirebase's so
 *      the FCM SDK binds OURS (which, being a subclass, still does everything
 *      RNFirebase's did). RNFirebase's service is left in place: if ours somehow
 *      doesn't win, the app simply falls back to the (slower) JS render — nothing
 *      breaks.
 *
 * NOTE: requires `expo prebuild --clean -p android` + a dev/EAS build to take
 * effect (a native change — not an OTA/JS update). After building, verify BOTH:
 * (a) an incoming call rings instantly on a killed+locked phone, and (b) normal
 * message push + FCM token refresh still work.
 */
const fs = require('fs');
const path = require('path');
const {
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
  AndroidConfig,
} = require('@expo/config-plugins');

const SERVICE_CLASS = 'CallMessagingService';
// react-native-firebase pulls firebase-messaging as `implementation` (BoM 34.8.0),
// so its classes (FirebaseMessagingService / RemoteMessage) are NOT exposed to the
// app's compile classpath — the app can see RNFirebase's own service but not its
// Google supertype. Adding the BoM + firebase-messaging to the app makes them
// visible so CallMessagingService compiles. Bare artifact (version via BoM) keeps
// it aligned with whatever RNFirebase resolves.
const GRADLE_MARKER = '// withCallFcmService: expose firebase-messaging to app classpath';
const GRADLE_BLOCK = `
${GRADLE_MARKER}
dependencies {
    implementation platform("com.google.firebase:firebase-bom:34.8.0")
    implementation "com.google.firebase:firebase-messaging"
}
`;

const serviceKotlin = (pkg) => `package ${pkg}

import com.google.firebase.messaging.RemoteMessage
import expo.modules.callui.ExpoCallUiModule
import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService

/**
 * GENERATED by plugins/withCallFcmService.js — do not edit here.
 *
 * Subclasses react-native-firebase's messaging service so onNewToken / send /
 * delivery callbacks are all preserved by inheritance. Adds native, instant
 * rendering of incoming-call pushes so a killed/locked phone rings WhatsApp-fast
 * instead of waiting for the RN JS runtime to cold-start.
 */
class ${SERVICE_CLASS} : ReactNativeFirebaseMessagingService() {
  override fun onMessageReceived(remoteMessage: RemoteMessage) {
    try {
      val data = remoteMessage.data
      // Caller hung up / ring timed out → dismiss the ringing notification NOW,
      // natively, so a killed callee's notification doesn't linger or arrive for
      // an already-dead call while the JS bridge cold-starts.
      if (data["type"] == "call_cancel") {
        ExpoCallUiModule.cancelIncoming(applicationContext, data["callId"])
        return
      }
      if (data["type"] == "call") {
        val ts = data["ts"]?.toLongOrNull() ?: 0L
        val fresh = ts <= 0L || (System.currentTimeMillis() - ts) <= STALE_CALL_PUSH_MS
        if (fresh) {
          ExpoCallUiModule.renderIncoming(applicationContext, data)
        }
        // Handled natively (or dropped as stale). RN-firebase delivers the message
        // to JS through its own broadcast receiver independently, so the JS
        // background handler still runs and merely refreshes the same callId
        // notification — no duplicate, no double-ring.
        return
      }
    } catch (t: Throwable) {
      // Never let a render error swallow a normal message — fall through.
    }
    super.onMessageReceived(remoteMessage)
  }

  companion object {
    // A call push older than the ring window is for a dead call — drop it.
    private const val STALE_CALL_PUSH_MS = 60_000L
  }
}
`;

const withServiceSource = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const pkg = AndroidConfig.Package.getPackage(cfg)
        || (cfg.android && cfg.android.package);
      if (!pkg) throw new Error('[withCallFcmService] android.package is not set');
      const projectRoot = cfg.modRequest.platformProjectRoot; // .../android
      const pkgDir = path.join(
        projectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.'),
      );
      fs.mkdirSync(pkgDir, { recursive: true });
      fs.writeFileSync(
        path.join(pkgDir, `${SERVICE_CLASS}.kt`),
        serviceKotlin(pkg),
        'utf8',
      );
      return cfg;
    },
  ]);

const withServiceManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults;
    const pkg = AndroidConfig.Package.getPackage(cfg)
      || (cfg.android && cfg.android.package);
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
    application.service = application.service || [];

    const fqName = `${pkg}.${SERVICE_CLASS}`;
    const already = application.service.some(
      (s) => s.$ && s.$['android:name'] === fqName,
    );
    if (!already) {
      application.service.push({
        $: { 'android:name': fqName, 'android:exported': 'false' },
        'intent-filter': [
          {
            // Higher than RNFirebase's default-priority (0) filter so the FCM SDK
            // binds OUR subclass. RNFirebase's service stays registered as a safe
            // fallback (subclass inherits it, so nothing is lost either way).
            $: { 'android:priority': '1' },
            action: [{ $: { 'android:name': 'com.google.firebase.MESSAGING_EVENT' } }],
          },
        ],
      });
    }
    return cfg;
  });

const withFirebaseMessagingDep = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') return cfg;
    if (!cfg.modResults.contents.includes(GRADLE_MARKER)) {
      cfg.modResults.contents += `\n${GRADLE_BLOCK}`;
    }
    return cfg;
  });

module.exports = (config) =>
  withFirebaseMessagingDep(withServiceManifest(withServiceSource(config)));
